apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-client
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-client
  template:
    metadata:
      labels:
        app: grpc-client
    spec:
      containers:
      - name: grpc-client
        image: grpc-client:latest
        imagePullPolicy: Never
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - "ps aux | grep client | grep -v grep"
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"