apiVersion: v1
kind: Service
metadata:
  name: server-service
  namespace: default
spec:
  selector:
    app: grpc-server
  ports:
  - protocol: TCP
    port: 50051
    targetPort: 50051
  type: ClusterIP